
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import SessionAuthProvider from "@/context/SessionAuthProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Prestamos 2023",
  description: "Generated by César Sánchez",
};

export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <div className="flex flex-col h-screen ">
          <div className="flex-1 flex flex-wrap">
            <SessionAuthProvider>
              <SideBar />
              <div className="flex-1 p-4 w-full md:w-1/2">{children}</div>
            </SessionAuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
