import "./globals.css";
import UpNavBar from "@/components/UpNavBar";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import HomePage from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prestamos 2023",
  description: "Generated by César Sánchez",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        <div className="flex flex-col h-screen bg-gray-100">
          {/* <!-- Barra de navegación superior --> */}
          <UpNavBar />
          {/* <!-- Contenido principal --> */}
          <div className="flex-1 flex flex-wrap">
            {/* <!-- Barra lateral de navegación (oculta en dispositivos pequeños) --> */}
            <SideBar />
            {/* <!-- Área de contenido principal --> */}
            <div className="flex-1 p-4 w-full md:w-1/2">
              {children}
              {/* <ExamplePage /> */}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
